# Generated by Django 3.0.1 on 2021-02-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210227_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='paid_books',
        ),
    ]
