# Generated by Django 3.0.1 on 2021-02-28 22:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_paid_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='paid_books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
