# Generated by Django 3.0.1 on 2021-03-02 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210228_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='paid_books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
