# Generated by Django 3.0.1 on 2021-02-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210226_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can add books!'), ('buyer', 'Can read bought books')]},
        ),
    ]
